// <auto-generated />
using System;
using MeetupAppCqrs.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetupAppCqrs.Migrations
{
    [DbContext(typeof(MeetupAppDbContext))]
    partial class MeetupAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("MeetupAppCqrs.Domain.FriendLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FriendUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("FriendLink");
                });

            modelBuilder.Entity("MeetupAppCqrs.Domain.Meetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAvailableSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Meetups");
                });

            modelBuilder.Entity("MeetupAppCqrs.Domain.SeatReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MeetupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId");

                    b.ToTable("SeatReservation");
                });

            modelBuilder.Entity("MeetupAppCqrs.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MeetupAppCqrs.Meetup.ReadModel.MeetupDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participants")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAvailableSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MeetupDetailsReadModel");
                });

            modelBuilder.Entity("MeetupAppCqrs.Meetup.ReadModel.UserSeatReservations", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatReservations")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSeatReservationsReadModel");
                });

            modelBuilder.Entity("MeetupAppCqrs.Domain.FriendLink", b =>
                {
                    b.HasOne("MeetupAppCqrs.Domain.UserProfile", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserProfileId");
                });

            modelBuilder.Entity("MeetupAppCqrs.Domain.SeatReservation", b =>
                {
                    b.HasOne("MeetupAppCqrs.Domain.Meetup", null)
                        .WithMany("SeatReservations")
                        .HasForeignKey("MeetupId");
                });
#pragma warning restore 612, 618
        }
    }
}
